# Generated by Django 3.2.4 on 2021-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=160, verbose_name='身長'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(default=0, verbose_name='性別'),
        ),
    ]
